### ISSUE TITLE
Bug when import

### ISSUE THREAD

**Issue by Chin-Z** [zst123/XHaloFloatingWindow#7]
With using  Internal API 16,I use Eclipse complie the sources and it's nothing change,xposed log show this:
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation.
it crash in MainXposed and code couldn't find any problems.

**Comment by Chin-Z** [comment]
Could you help me?

**Comment by zst123** [comment]
It means it was not compiled properly. Try to "Clean" the project (Project > Clean) and recompile. If it didn't work, try re-downloading the internal api's

**Comment by bhavesh4uonly** [comment]
I'm also getting the same exception while building XHaloFloatingWindow source. Can you please tell me which version of XposedBridge jar to be used while compiling XHaloFloatingWindow? The strange thing is when I download the XHaloFloatingWindow module from XposedInstaller app, module works well but when I build on my local machine and install on device, it fails and I always get the "module inactive" message.

Note that I've already tried your proposed solution above i.e "Cleaning the project in Eclipse". I'm using the android-16-internal APIs as listed by you. 

Please help me to get this issue resolved.

Thanks,

**Comment by zst123** [comment]
Hi bhavesh4uonly,

You can use XposedBridgeApi.jar as old as v2.1 and above. Try to remove all the libraries .jar and add them again. 
http://stackoverflow.com/questions/11155340/java-lang-illegalaccesserror-class-ref-in-pre-verified-class-resolved-to-unexpe
http://stackoverflow.com/questions/15605898/java-lang-illegalaccesserror-class-ref-in-preverified-class-resolved-to-unexpect

**Comment by zst123** [comment]
Closed. Project no longer needs to use internal APIs.

https://github.com/zst123/XHaloFloatingWindow/commit/b27975136374d00f6f17ec61121dd00396deb4d2
https://github.com/zst123/XHaloFloatingWindow/commit/d14bfc237d2d41dd7af16e055932401c1c22ff7c
